# Generated by Django 5.0.7 on 2024-08-30 16:54

import django.core.validators
import journey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimage',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='documents/file/'),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['jpeg']), journey.models.validate_image]),
        ),
    ]
