# Generated by Django 5.0.7 on 2024-08-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0007_documentimage_files_alter_documentimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentimage',
            name='files',
        ),
    ]
