# Generated by Django 5.1.5 on 2025-01-20 18:47

import django.core.validators
import journey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0010_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'pdf', 'png', 'jpg']), journey.models.validate_image]),
        ),
    ]
